import { ReactNode } from "react";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Head } from "./Head";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <Head />
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
